replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3

backendImage:
  repository: granthynd/blog_backend
  pullPolicy: Always
  tag: "latest"

frontendImage:
  repository: granthynd/blog_frontend
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  backend:
    externalPort: 8000
    internalPort: 8000
    internalPortName: backend-http
  frontend:
    externalPort: 3000
    internalPort: 3000
    internalPortName: frontend-http

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: backend.granthynd.com
      paths:
        - path: /
          pathType: Prefix
          port: 8000
    - host: granthynd.com
      paths:
        - path: /
          pathType: Prefix
          port: 3000
  tls:
    - hosts:
        - backend.granthynd.com
        - granthynd.com
      secretName: letsencrypt-production

resources:
  backend:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 200m
      memory: 200Mi
  frontend:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 50m
      memory: 50Mi

# Backend secret vars supplied by CI
backendEnvVars: {}

securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}
