apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "blog.fullname" . }}
  labels:
    {{- include "blog.labels" . | nindent 4 }}

spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "blog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "blog.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "blog.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-backend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.backendImage.repository }}:{{ .Values.backendImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backendImage.pullPolicy }}
          env: 
            {{- range .Values.backendEnvVars }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
          args: ["gunicorn", "-w", "3", "-b", "0.0.0.0:{{ .Values.service.backend.internalPort }}", "blog.wsgi:application"]
          ports:
            - name: {{ .Values.service.backend.internalPortName }}
              containerPort: {{ .Values.service.backend.internalPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources.backend | nindent 12 }}
        - name: {{ .Chart.Name }}-frontend
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontendImage.repository }}:{{ .Values.frontendImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontendImage.pullPolicy }}
          args: ["serve", "-s", "-l", "{{ .Values.service.frontend.internalPort }}", "build"]
          stdin: true
          tty: true
          ports:
            - name: {{ .Values.service.frontend.internalPortName }}
              containerPort: {{ .Values.service.frontend.internalPort }}
              protocol: TCP 
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}