apiVersion: networking.k8s.io/v1
kind: IngressClass

metadata:
  name: nginx
  labels:
    app.kubernetes.io/component: controller
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"

spec:
  controller: kubernetes.github.io/ingress-nginx
