apiVersion: v1
kind: Service

metadata:
  name: {{ include "blog.fullname" . }}
  labels: {{ - include "blog.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.backend.externalPort }}
      targetPort: {{ .Values.service.backend.internalPort }}
      protocol: TCP
      name: backend-service
    - port: {{ .Values.service.frontend.externalPort }}
      targetPort: {{ .Values.service.frontend.internalPort }}
      protocol: TCP
      name: frontend-service
  selector: {{ - include "blog.selectorLabels" . | nindent 4 }}
